services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  react-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production