services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  react-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "80:80"