FROM node:20 AS build
WORKDIR /app
COPY app/package.json app/package-lock.json ./
RUN npm install
COPY app .
ARG VITE_API_URL
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]